version: '3.8'
services:
  authservice:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: mongodb://mongodb:27017/user_authentication
    volumes:
      - logs:/app/logs

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db

volumes:
  data:
  logs:
